version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: bao/hello-circleci

workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only

