version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-with-docker:
    steps:
      - checkout
      - build
        image: docker/mcr.microsoft.com/dotnet/core/sdk:3.1

workflows:
  build-image:
    jobs:
      - build-with-docker

